#ifndef EDITOR_KEYS_H
#define EDITOR_KEYS_H

#include <stddef.h>
#include <stdint.h>
#include "x11/plat.h"

/* Sublime Text Linux, installed build 4200, normal editor defaults.
 * IDs describe intent, not an executor. UNIMPLEMENTED means view.h cannot
 * execute the complete command (even if some other module offers primitives).
 * Ordinary printable input is not a binding: insert plat_event.utf8 on NONE.
 * Release/non-key events must not be passed to keys_lookup. */
typedef enum keys_action {
    KEYS_ACTION_NONE,
    KEYS_ACTION_CHORD,
    KEYS_ACTION_LEFT, KEYS_ACTION_RIGHT,
    KEYS_ACTION_UP, KEYS_ACTION_DOWN,
    KEYS_ACTION_WORD_LEFT, KEYS_ACTION_WORD_RIGHT,
    KEYS_ACTION_SUBWORD_LEFT, KEYS_ACTION_SUBWORD_RIGHT,
    KEYS_ACTION_PAGE_UP, KEYS_ACTION_PAGE_DOWN,
    KEYS_ACTION_HOME, KEYS_ACTION_END,
    KEYS_ACTION_DOC_HOME, KEYS_ACTION_DOC_END,
    KEYS_ACTION_SELECT_ALL, KEYS_ACTION_SELECT_LINE,
    KEYS_ACTION_SELECT_PREVIOUS_LINE,
    KEYS_ACTION_BACKSPACE, KEYS_ACTION_DELETE,
    KEYS_ACTION_WORD_BACKSPACE, KEYS_ACTION_WORD_DELETE,
    KEYS_ACTION_INSERT,
    KEYS_ACTION_UNDO, KEYS_ACTION_REDO, KEYS_ACTION_REDO_OR_REPEAT,
    KEYS_ACTION_SOFT_UNDO, KEYS_ACTION_SOFT_REDO,
    KEYS_ACTION_CUT, KEYS_ACTION_COPY, KEYS_ACTION_PASTE,
    KEYS_ACTION_PASTE_AND_INDENT, KEYS_ACTION_PASTE_HISTORY,
    KEYS_ACTION_SPLIT_SELECTION_LINES, KEYS_ACTION_ADD_NEXT_OCCURRENCE,
    KEYS_ACTION_SKIP_NEXT_OCCURRENCE, KEYS_ACTION_COLUMN_SELECTION,
    KEYS_ACTION_CANCEL, KEYS_ACTION_INDENT, KEYS_ACTION_UNINDENT,
    KEYS_ACTION_REINDENT, KEYS_ACTION_TOGGLE_OVERWRITE,
    KEYS_ACTION_SELECT_SCOPE, KEYS_ACTION_SELECT_SMART,
    KEYS_ACTION_SELECT_BRACKETS, KEYS_ACTION_GOTO_BRACKET,
    KEYS_ACTION_CLOSE_TAG, KEYS_ACTION_RECORD_MACRO, KEYS_ACTION_RUN_MACRO,
    KEYS_ACTION_INSERT_LINE_AFTER, KEYS_ACTION_INSERT_LINE_BEFORE,
    KEYS_ACTION_GOTO_FILE, KEYS_ACTION_COMMAND_PALETTE,
    KEYS_ACTION_SELECT_WORKSPACE, KEYS_ACTION_GOTO_SYMBOL,
    KEYS_ACTION_GOTO_LINE, KEYS_ACTION_GOTO_WORD,
    KEYS_ACTION_GOTO_DEFINITION, KEYS_ACTION_GOTO_REFERENCE,
    KEYS_ACTION_GOTO_PROJECT_SYMBOL, KEYS_ACTION_JUMP_BACK,
    KEYS_ACTION_JUMP_FORWARD, KEYS_ACTION_INCREMENTAL_FIND,
    KEYS_ACTION_FIND, KEYS_ACTION_REPLACE, KEYS_ACTION_REPLACE_NEXT,
    KEYS_ACTION_FIND_NEXT, KEYS_ACTION_FIND_PREVIOUS,
    KEYS_ACTION_FIND_UNDER, KEYS_ACTION_FIND_UNDER_PREVIOUS,
    KEYS_ACTION_FIND_ALL_UNDER, KEYS_ACTION_SLURP_FIND,
    KEYS_ACTION_SLURP_REPLACE, KEYS_ACTION_FIND_IN_FILES,
    KEYS_ACTION_NEXT_RESULT, KEYS_ACTION_PREVIOUS_RESULT,
    KEYS_ACTION_NEXT_MODIFICATION, KEYS_ACTION_PREVIOUS_MODIFICATION,
    KEYS_ACTION_REVERT_HUNK, KEYS_ACTION_REVERT_MODIFICATION,
    KEYS_ACTION_INLINE_DIFF, KEYS_ACTION_SPELL_CHECK,
    KEYS_ACTION_NEXT_MISSPELLING, KEYS_ACTION_PREVIOUS_MISSPELLING,
    KEYS_ACTION_MOVE_LINE_UP, KEYS_ACTION_MOVE_LINE_DOWN,
    KEYS_ACTION_DELETE_TO_BOL, KEYS_ACTION_DELETE_TO_EOL,
    KEYS_ACTION_TOGGLE_COMMENT, KEYS_ACTION_PRIMARY_J_CHANGED,
    KEYS_ACTION_JOIN_LINES, KEYS_ACTION_DUPLICATE_LINE,
    KEYS_ACTION_CONSOLE, KEYS_ACTION_AUTO_COMPLETE, KEYS_ACTION_SHOW_SCOPE,
    KEYS_ACTION_BUILD, KEYS_ACTION_CANCEL_BUILD,
    KEYS_ACTION_TRANSPOSE, KEYS_ACTION_SORT_LINES,
    KEYS_ACTION_SET_LAYOUT, KEYS_ACTION_FOCUS_GROUP,
    KEYS_ACTION_MOVE_TO_GROUP, KEYS_ACTION_FOCUS_SIDEBAR,
    KEYS_ACTION_NEW_PANE, KEYS_ACTION_CLOSE_PANE,
    KEYS_ACTION_FOCUS_NEIGHBOR_GROUP, KEYS_ACTION_MOVE_NEIGHBOR_GROUP,
    KEYS_ACTION_SELECT_TAB, KEYS_ACTION_SELECT_LAST_TAB,
    KEYS_ACTION_UNSELECT_OTHERS, KEYS_ACTION_UNSELECT_LEFT,
    KEYS_ACTION_UNSELECT_RIGHT, KEYS_ACTION_SELECT_LEFT,
    KEYS_ACTION_SELECT_RIGHT, KEYS_ACTION_FOCUS_LEFT, KEYS_ACTION_FOCUS_RIGHT,
    KEYS_ACTION_NEXT_BOOKMARK, KEYS_ACTION_PREVIOUS_BOOKMARK,
    KEYS_ACTION_TOGGLE_BOOKMARK, KEYS_ACTION_CLEAR_BOOKMARKS,
    KEYS_ACTION_SELECT_BOOKMARKS, KEYS_ACTION_DELETE_LINE,
    KEYS_ACTION_WRAP_LINES, KEYS_ACTION_UPPER_CASE, KEYS_ACTION_LOWER_CASE,
    KEYS_ACTION_SET_MARK, KEYS_ACTION_SELECT_TO_MARK,
    KEYS_ACTION_DELETE_TO_MARK, KEYS_ACTION_SWAP_MARK, KEYS_ACTION_YANK,
    KEYS_ACTION_CLEAR_MARK, KEYS_ACTION_SHOW_AT_CENTER,
    KEYS_ACTION_FONT_SIZE, KEYS_ACTION_XML_TAG_SNIPPET,
    KEYS_ACTION_FOLD, KEYS_ACTION_UNFOLD, KEYS_ACTION_FOLD_LEVEL,
    KEYS_ACTION_UNFOLD_ALL, KEYS_ACTION_FOLD_TAG_ATTRIBUTES,
    KEYS_ACTION_CONTEXT_MENU, KEYS_ACTION_EXIT, KEYS_ACTION_NEW_WINDOW,
    KEYS_ACTION_CLOSE_WINDOW, KEYS_ACTION_OPEN_FILE,
    KEYS_ACTION_REOPEN_FILE, KEYS_ACTION_SWITCH_FILE,
    KEYS_ACTION_NEW_FILE, KEYS_ACTION_SAVE, KEYS_ACTION_SAVE_AS,
    KEYS_ACTION_CLOSE_FILE, KEYS_ACTION_CLOSE,
    KEYS_ACTION_TOGGLE_SIDEBAR, KEYS_ACTION_FULL_SCREEN,
    KEYS_ACTION_DISTRACTION_FREE, KEYS_ACTION_SCROLL_LINES,
    KEYS_ACTION_NEXT_VIEW, KEYS_ACTION_PREVIOUS_VIEW,
    KEYS_ACTION_NEXT_VIEW_STACK, KEYS_ACTION_PREVIOUS_VIEW_STACK,
    KEYS_ACTION_COUNT
} keys_action;

#define KEYS_ARG_EXTEND        UINT16_C(1)
#define KEYS_ARG_UNIMPLEMENTED UINT16_C(2)
#define KEYS_ARG_BLOCK         UINT16_C(4)
#define KEYS_ARG_SIDE_BY_SIDE  UINT16_C(8) /* also clear views to right */
#define KEYS_ARG_REVERSE       UINT16_C(16)
#define KEYS_ARG_SELECT        UINT16_C(32)
#define KEYS_ARG_CASE_SENSITIVE UINT16_C(64)
#define KEYS_ARG_PREFER_HIDE   UINT16_C(128)
#define KEYS_ARG_NO_MOVE       UINT16_C(256)
#define KEYS_ARG_SINGLE_LINE   UINT16_C(512)

typedef enum keys_chord {
    KEYS_CHORD_NONE, KEYS_CHORD_K, KEYS_CHORD_J, KEYS_CHORD_COUNT
} keys_chord;

typedef struct keys_args {
    uint16_t flags;
    int16_t value; /* INSERT: Unicode ASCII; column +/-1; scroll +/-1;
                   * group/tab: zero-based; layout: Linux digit preset;
                   * fold: level; font: +/-1; CHORD: next keys_chord. */
    uint8_t chord; /* namespace of this stroke; NONE = standalone/prefix */
} keys_args;

typedef struct keys_binding {
    uint16_t modifiers; /* PLAT_MOD_*; excludes lock bits */
    uint32_t keysym;    /* XKB_KEY_*; canonical ASCII lowercase */
    keys_action action;
    keys_args args;
} keys_binding;

/* Zero initialize once per input owner. Reset on focus/keymap/view changes.
 * No timeout/clock hidden in lookup; caller may reset on its own timeout. */
typedef struct keys_state { uint8_t chord; } keys_state;
typedef enum keys_result {
    KEYS_NONE, KEYS_MATCH, KEYS_PREFIX, KEYS_CANCELLED, KEYS_ERR_ARG
} keys_result;

void keys_reset(keys_state *state); /* NULL is allowed */
/* Read-only table sorted by (args.chord, modifiers, keysym). No allocation.
 * Returned storage has process lifetime; count is optional. */
const keys_binding *keys_defaults(size_t *count);
/* O(log n), no allocation. out is cleared except on MATCH/PREFIX.
 * Lock bits ignored; unknown modifier bits and AltGr never match shortcuts.
 * ASCII uppercase, ISO_Left_Tab, keypad navigation, and US shifted shortcut
 * punctuation are canonicalized. No arbitrary layout transliteration.
 * Bare modifier presses preserve a pending chord. A mismatched second stroke
 * consumes/cancels the chord (no standalone replay); Escape cancels it too.
 * A corrupt chord byte resets to NONE before looking up the current stroke.
 * NONE permits normal text; PREFIX/CANCELLED consume input; MATCH may carry
 * UNIMPLEMENTED, in which case the caller must consume without editing. */
keys_result keys_lookup(keys_state *state, uint32_t keysym, uint16_t modifiers,
                        const keys_binding **out);

#endif
