#include "keys/keys.h"
#include <xkbcommon/xkbcommon-keysyms.h>

/* Normal editor defaults, source: installed Default.sublime-package build
 * 4200. Sorted numerically by (chord, modifiers, keysym). Do not sort at
 * runtime or share this data with the independent test expectations. */
static const keys_binding defaults[] = {
    {0, XKB_KEY_BackSpace, KEYS_ACTION_BACKSPACE, {0, 0, KEYS_CHORD_NONE}}, /* backspace */
    {0, XKB_KEY_Tab, KEYS_ACTION_INSERT, {0, 9, KEYS_CHORD_NONE}}, /* tab */
    {0, XKB_KEY_Return, KEYS_ACTION_INSERT, {0, 10, KEYS_CHORD_NONE}}, /* enter */
    {0, XKB_KEY_Escape, KEYS_ACTION_CANCEL, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* escape */
    {0, XKB_KEY_Home, KEYS_ACTION_HOME, {0, 0, KEYS_CHORD_NONE}}, /* home */
    {0, XKB_KEY_Left, KEYS_ACTION_LEFT, {0, 0, KEYS_CHORD_NONE}}, /* left */
    {0, XKB_KEY_Up, KEYS_ACTION_UP, {0, 0, KEYS_CHORD_NONE}}, /* up */
    {0, XKB_KEY_Right, KEYS_ACTION_RIGHT, {0, 0, KEYS_CHORD_NONE}}, /* right */
    {0, XKB_KEY_Down, KEYS_ACTION_DOWN, {0, 0, KEYS_CHORD_NONE}}, /* down */
    {0, XKB_KEY_Prior, KEYS_ACTION_PAGE_UP, {0, 0, KEYS_CHORD_NONE}}, /* pageup */
    {0, XKB_KEY_Next, KEYS_ACTION_PAGE_DOWN, {0, 0, KEYS_CHORD_NONE}}, /* pagedown */
    {0, XKB_KEY_End, KEYS_ACTION_END, {0, 0, KEYS_CHORD_NONE}}, /* end */
    {0, XKB_KEY_Insert, KEYS_ACTION_TOGGLE_OVERWRITE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* insert */
    {0, XKB_KEY_Undo, KEYS_ACTION_UNDO, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* undo */
    {0, XKB_KEY_Redo, KEYS_ACTION_REDO_OR_REPEAT, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* redo */
    {0, XKB_KEY_Menu, KEYS_ACTION_CONTEXT_MENU, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* context_menu */
    {0, XKB_KEY_Find, KEYS_ACTION_FIND, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* find */
    {0, XKB_KEY_KP_Enter, KEYS_ACTION_INSERT, {0, 10, KEYS_CHORD_NONE}}, /* keypad_enter */
    {0, XKB_KEY_F2, KEYS_ACTION_NEXT_BOOKMARK, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* f2 */
    {0, XKB_KEY_F3, KEYS_ACTION_FIND_NEXT, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* f3 */
    {0, XKB_KEY_F4, KEYS_ACTION_NEXT_RESULT, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* f4 */
    {0, XKB_KEY_F6, KEYS_ACTION_SPELL_CHECK, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* f6 */
    {0, XKB_KEY_F7, KEYS_ACTION_BUILD, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* f7 */
    {0, XKB_KEY_F9, KEYS_ACTION_SORT_LINES, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* f9 */
    {0, XKB_KEY_F11, KEYS_ACTION_FULL_SCREEN, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* f11 */
    {0, XKB_KEY_F12, KEYS_ACTION_GOTO_DEFINITION, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* f12 */
    {0, XKB_KEY_Delete, KEYS_ACTION_DELETE, {0, 0, KEYS_CHORD_NONE}}, /* delete */
    {0, XKB_KEY_XF86Close, KEYS_ACTION_CLOSE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* close */
    {0, XKB_KEY_XF86Copy, KEYS_ACTION_COPY, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* copy */
    {0, XKB_KEY_XF86Cut, KEYS_ACTION_CUT, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* cut */
    {0, XKB_KEY_XF86Open, KEYS_ACTION_OPEN_FILE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* open */
    {0, XKB_KEY_XF86Paste, KEYS_ACTION_PASTE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* paste */
    {0, XKB_KEY_XF86Save, KEYS_ACTION_SAVE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* save */
    {PLAT_MOD_SHIFT, XKB_KEY_BackSpace, KEYS_ACTION_BACKSPACE, {0, 0, KEYS_CHORD_NONE}}, /* shift+backspace */
    {PLAT_MOD_SHIFT, XKB_KEY_Tab, KEYS_ACTION_UNINDENT, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* shift+tab */
    {PLAT_MOD_SHIFT, XKB_KEY_Return, KEYS_ACTION_INSERT, {0, 10, KEYS_CHORD_NONE}}, /* shift+enter */
    {PLAT_MOD_SHIFT, XKB_KEY_Home, KEYS_ACTION_HOME, {KEYS_ARG_EXTEND, 0, KEYS_CHORD_NONE}}, /* shift+home */
    {PLAT_MOD_SHIFT, XKB_KEY_Left, KEYS_ACTION_LEFT, {KEYS_ARG_EXTEND, 0, KEYS_CHORD_NONE}}, /* shift+left */
    {PLAT_MOD_SHIFT, XKB_KEY_Up, KEYS_ACTION_UP, {KEYS_ARG_EXTEND, 0, KEYS_CHORD_NONE}}, /* shift+up */
    {PLAT_MOD_SHIFT, XKB_KEY_Right, KEYS_ACTION_RIGHT, {KEYS_ARG_EXTEND, 0, KEYS_CHORD_NONE}}, /* shift+right */
    {PLAT_MOD_SHIFT, XKB_KEY_Down, KEYS_ACTION_DOWN, {KEYS_ARG_EXTEND, 0, KEYS_CHORD_NONE}}, /* shift+down */
    {PLAT_MOD_SHIFT, XKB_KEY_Prior, KEYS_ACTION_PAGE_UP, {KEYS_ARG_EXTEND, 0, KEYS_CHORD_NONE}}, /* shift+pageup */
    {PLAT_MOD_SHIFT, XKB_KEY_Next, KEYS_ACTION_PAGE_DOWN, {KEYS_ARG_EXTEND, 0, KEYS_CHORD_NONE}}, /* shift+pagedown */
    {PLAT_MOD_SHIFT, XKB_KEY_End, KEYS_ACTION_END, {KEYS_ARG_EXTEND, 0, KEYS_CHORD_NONE}}, /* shift+end */
    {PLAT_MOD_SHIFT, XKB_KEY_Insert, KEYS_ACTION_PASTE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* shift+insert */
    {PLAT_MOD_SHIFT, XKB_KEY_KP_Enter, KEYS_ACTION_INSERT, {0, 10, KEYS_CHORD_NONE}}, /* shift+keypad_enter */
    {PLAT_MOD_SHIFT, XKB_KEY_F2, KEYS_ACTION_PREVIOUS_BOOKMARK, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* shift+f2 */
    {PLAT_MOD_SHIFT, XKB_KEY_F3, KEYS_ACTION_FIND_PREVIOUS, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* shift+f3 */
    {PLAT_MOD_SHIFT, XKB_KEY_F4, KEYS_ACTION_PREVIOUS_RESULT, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* shift+f4 */
    {PLAT_MOD_SHIFT, XKB_KEY_F10, KEYS_ACTION_CONTEXT_MENU, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* shift+f10 */
    {PLAT_MOD_SHIFT, XKB_KEY_F11, KEYS_ACTION_DISTRACTION_FREE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* shift+f11 */
    {PLAT_MOD_SHIFT, XKB_KEY_F12, KEYS_ACTION_GOTO_REFERENCE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* shift+f12 */
    {PLAT_MOD_SHIFT, XKB_KEY_Delete, KEYS_ACTION_CUT, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* shift+delete */
    {PLAT_MOD_CTRL, XKB_KEY_space, KEYS_ACTION_AUTO_COMPLETE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+space */
    {PLAT_MOD_CTRL, XKB_KEY_plus, KEYS_ACTION_FONT_SIZE, {KEYS_ARG_UNIMPLEMENTED, 1, KEYS_CHORD_NONE}}, /* ctrl++ */
    {PLAT_MOD_CTRL, XKB_KEY_comma, KEYS_ACTION_PREVIOUS_MODIFICATION, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+, */
    {PLAT_MOD_CTRL, XKB_KEY_minus, KEYS_ACTION_FONT_SIZE, {KEYS_ARG_UNIMPLEMENTED, -1, KEYS_CHORD_NONE}}, /* ctrl+- */
    {PLAT_MOD_CTRL, XKB_KEY_period, KEYS_ACTION_NEXT_MODIFICATION, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+. */
    {PLAT_MOD_CTRL, XKB_KEY_slash, KEYS_ACTION_TOGGLE_COMMENT, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+/ */
    {PLAT_MOD_CTRL, XKB_KEY_0, KEYS_ACTION_FOCUS_SIDEBAR, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+0 */
    {PLAT_MOD_CTRL, XKB_KEY_1, KEYS_ACTION_FOCUS_GROUP, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+1 */
    {PLAT_MOD_CTRL, XKB_KEY_2, KEYS_ACTION_FOCUS_GROUP, {KEYS_ARG_UNIMPLEMENTED, 1, KEYS_CHORD_NONE}}, /* ctrl+2 */
    {PLAT_MOD_CTRL, XKB_KEY_3, KEYS_ACTION_FOCUS_GROUP, {KEYS_ARG_UNIMPLEMENTED, 2, KEYS_CHORD_NONE}}, /* ctrl+3 */
    {PLAT_MOD_CTRL, XKB_KEY_4, KEYS_ACTION_FOCUS_GROUP, {KEYS_ARG_UNIMPLEMENTED, 3, KEYS_CHORD_NONE}}, /* ctrl+4 */
    {PLAT_MOD_CTRL, XKB_KEY_5, KEYS_ACTION_FOCUS_GROUP, {KEYS_ARG_UNIMPLEMENTED, 4, KEYS_CHORD_NONE}}, /* ctrl+5 */
    {PLAT_MOD_CTRL, XKB_KEY_6, KEYS_ACTION_FOCUS_GROUP, {KEYS_ARG_UNIMPLEMENTED, 5, KEYS_CHORD_NONE}}, /* ctrl+6 */
    {PLAT_MOD_CTRL, XKB_KEY_7, KEYS_ACTION_FOCUS_GROUP, {KEYS_ARG_UNIMPLEMENTED, 6, KEYS_CHORD_NONE}}, /* ctrl+7 */
    {PLAT_MOD_CTRL, XKB_KEY_8, KEYS_ACTION_FOCUS_GROUP, {KEYS_ARG_UNIMPLEMENTED, 7, KEYS_CHORD_NONE}}, /* ctrl+8 */
    {PLAT_MOD_CTRL, XKB_KEY_9, KEYS_ACTION_FOCUS_GROUP, {KEYS_ARG_UNIMPLEMENTED, 8, KEYS_CHORD_NONE}}, /* ctrl+9 */
    {PLAT_MOD_CTRL, XKB_KEY_semicolon, KEYS_ACTION_GOTO_WORD, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+; */
    {PLAT_MOD_CTRL, XKB_KEY_equal, KEYS_ACTION_FONT_SIZE, {KEYS_ARG_UNIMPLEMENTED, 1, KEYS_CHORD_NONE}}, /* ctrl+= */
    {PLAT_MOD_CTRL, XKB_KEY_bracketleft, KEYS_ACTION_UNINDENT, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+[ */
    {PLAT_MOD_CTRL, XKB_KEY_bracketright, KEYS_ACTION_INDENT, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+] */
    {PLAT_MOD_CTRL, XKB_KEY_grave, KEYS_ACTION_CONSOLE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+` */
    {PLAT_MOD_CTRL, XKB_KEY_a, KEYS_ACTION_SELECT_ALL, {0, 0, KEYS_CHORD_NONE}}, /* ctrl+a */
    {PLAT_MOD_CTRL, XKB_KEY_b, KEYS_ACTION_BUILD, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+b */
    {PLAT_MOD_CTRL, XKB_KEY_c, KEYS_ACTION_COPY, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+c */
    {PLAT_MOD_CTRL, XKB_KEY_d, KEYS_ACTION_ADD_NEXT_OCCURRENCE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+d */
    {PLAT_MOD_CTRL, XKB_KEY_e, KEYS_ACTION_SLURP_FIND, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+e */
    {PLAT_MOD_CTRL, XKB_KEY_f, KEYS_ACTION_FIND, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+f */
    {PLAT_MOD_CTRL, XKB_KEY_g, KEYS_ACTION_GOTO_LINE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+g */
    {PLAT_MOD_CTRL, XKB_KEY_h, KEYS_ACTION_REPLACE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+h */
    {PLAT_MOD_CTRL, XKB_KEY_i, KEYS_ACTION_INCREMENTAL_FIND, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+i */
    {PLAT_MOD_CTRL, XKB_KEY_j, KEYS_ACTION_CHORD, {0, 2, KEYS_CHORD_NONE}}, /* ctrl+j */
    {PLAT_MOD_CTRL, XKB_KEY_k, KEYS_ACTION_CHORD, {0, 1, KEYS_CHORD_NONE}}, /* ctrl+k */
    {PLAT_MOD_CTRL, XKB_KEY_l, KEYS_ACTION_SELECT_LINE, {0, 0, KEYS_CHORD_NONE}}, /* ctrl+l */
    {PLAT_MOD_CTRL, XKB_KEY_m, KEYS_ACTION_GOTO_BRACKET, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+m */
    {PLAT_MOD_CTRL, XKB_KEY_n, KEYS_ACTION_NEW_FILE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+n */
    {PLAT_MOD_CTRL, XKB_KEY_o, KEYS_ACTION_OPEN_FILE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+o */
    {PLAT_MOD_CTRL, XKB_KEY_p, KEYS_ACTION_GOTO_FILE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+p */
    {PLAT_MOD_CTRL, XKB_KEY_q, KEYS_ACTION_EXIT, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+q */
    {PLAT_MOD_CTRL, XKB_KEY_r, KEYS_ACTION_GOTO_SYMBOL, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+r */
    {PLAT_MOD_CTRL, XKB_KEY_s, KEYS_ACTION_SAVE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+s */
    {PLAT_MOD_CTRL, XKB_KEY_t, KEYS_ACTION_TRANSPOSE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+t */
    {PLAT_MOD_CTRL, XKB_KEY_u, KEYS_ACTION_SOFT_UNDO, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+u */
    {PLAT_MOD_CTRL, XKB_KEY_v, KEYS_ACTION_PASTE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+v */
    {PLAT_MOD_CTRL, XKB_KEY_w, KEYS_ACTION_CLOSE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+w */
    {PLAT_MOD_CTRL, XKB_KEY_x, KEYS_ACTION_CUT, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+x */
    {PLAT_MOD_CTRL, XKB_KEY_y, KEYS_ACTION_REDO_OR_REPEAT, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+y */
    {PLAT_MOD_CTRL, XKB_KEY_z, KEYS_ACTION_UNDO, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+z */
    {PLAT_MOD_CTRL, XKB_KEY_BackSpace, KEYS_ACTION_WORD_BACKSPACE, {0, 0, KEYS_CHORD_NONE}}, /* ctrl+backspace */
    {PLAT_MOD_CTRL, XKB_KEY_Tab, KEYS_ACTION_NEXT_VIEW_STACK, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+tab */
    {PLAT_MOD_CTRL, XKB_KEY_Return, KEYS_ACTION_INSERT_LINE_AFTER, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+enter */
    {PLAT_MOD_CTRL, XKB_KEY_Home, KEYS_ACTION_DOC_HOME, {0, 0, KEYS_CHORD_NONE}}, /* ctrl+home */
    {PLAT_MOD_CTRL, XKB_KEY_Left, KEYS_ACTION_WORD_LEFT, {0, 0, KEYS_CHORD_NONE}}, /* ctrl+left */
    {PLAT_MOD_CTRL, XKB_KEY_Up, KEYS_ACTION_SCROLL_LINES, {KEYS_ARG_UNIMPLEMENTED, 1, KEYS_CHORD_NONE}}, /* ctrl+up */
    {PLAT_MOD_CTRL, XKB_KEY_Right, KEYS_ACTION_WORD_RIGHT, {0, 0, KEYS_CHORD_NONE}}, /* ctrl+right */
    {PLAT_MOD_CTRL, XKB_KEY_Down, KEYS_ACTION_SCROLL_LINES, {KEYS_ARG_UNIMPLEMENTED, -1, KEYS_CHORD_NONE}}, /* ctrl+down */
    {PLAT_MOD_CTRL, XKB_KEY_Prior, KEYS_ACTION_PREVIOUS_VIEW, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+pageup */
    {PLAT_MOD_CTRL, XKB_KEY_Next, KEYS_ACTION_NEXT_VIEW, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+pagedown */
    {PLAT_MOD_CTRL, XKB_KEY_End, KEYS_ACTION_DOC_END, {0, 0, KEYS_CHORD_NONE}}, /* ctrl+end */
    {PLAT_MOD_CTRL, XKB_KEY_Insert, KEYS_ACTION_COPY, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+insert */
    {PLAT_MOD_CTRL, XKB_KEY_Break, KEYS_ACTION_CANCEL_BUILD, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+break */
    {PLAT_MOD_CTRL, XKB_KEY_KP_Enter, KEYS_ACTION_INSERT_LINE_AFTER, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+keypad_enter */
    {PLAT_MOD_CTRL, XKB_KEY_F2, KEYS_ACTION_TOGGLE_BOOKMARK, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+f2 */
    {PLAT_MOD_CTRL, XKB_KEY_F3, KEYS_ACTION_FIND_UNDER, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+f3 */
    {PLAT_MOD_CTRL, XKB_KEY_F4, KEYS_ACTION_CLOSE_FILE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+f4 */
    {PLAT_MOD_CTRL, XKB_KEY_F6, KEYS_ACTION_NEXT_MISSPELLING, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+f6 */
    {PLAT_MOD_CTRL, XKB_KEY_F9, KEYS_ACTION_SORT_LINES, {KEYS_ARG_UNIMPLEMENTED|KEYS_ARG_CASE_SENSITIVE, 0, KEYS_CHORD_NONE}}, /* ctrl+f9 */
    {PLAT_MOD_CTRL, XKB_KEY_F12, KEYS_ACTION_GOTO_DEFINITION, {KEYS_ARG_UNIMPLEMENTED|KEYS_ARG_SIDE_BY_SIDE, 0, KEYS_CHORD_NONE}}, /* ctrl+f12 */
    {PLAT_MOD_CTRL, XKB_KEY_Delete, KEYS_ACTION_WORD_DELETE, {0, 0, KEYS_CHORD_NONE}}, /* ctrl+delete */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_space, KEYS_ACTION_SELECT_SCOPE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+space */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_slash, KEYS_ACTION_TOGGLE_COMMENT, {KEYS_ARG_UNIMPLEMENTED|KEYS_ARG_BLOCK, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+/ */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_1, KEYS_ACTION_MOVE_TO_GROUP, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+1 */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_2, KEYS_ACTION_MOVE_TO_GROUP, {KEYS_ARG_UNIMPLEMENTED, 1, KEYS_CHORD_NONE}}, /* ctrl+shift+2 */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_3, KEYS_ACTION_MOVE_TO_GROUP, {KEYS_ARG_UNIMPLEMENTED, 2, KEYS_CHORD_NONE}}, /* ctrl+shift+3 */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_4, KEYS_ACTION_MOVE_TO_GROUP, {KEYS_ARG_UNIMPLEMENTED, 3, KEYS_CHORD_NONE}}, /* ctrl+shift+4 */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_5, KEYS_ACTION_MOVE_TO_GROUP, {KEYS_ARG_UNIMPLEMENTED, 4, KEYS_CHORD_NONE}}, /* ctrl+shift+5 */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_6, KEYS_ACTION_MOVE_TO_GROUP, {KEYS_ARG_UNIMPLEMENTED, 5, KEYS_CHORD_NONE}}, /* ctrl+shift+6 */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_7, KEYS_ACTION_MOVE_TO_GROUP, {KEYS_ARG_UNIMPLEMENTED, 6, KEYS_CHORD_NONE}}, /* ctrl+shift+7 */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_8, KEYS_ACTION_MOVE_TO_GROUP, {KEYS_ARG_UNIMPLEMENTED, 7, KEYS_CHORD_NONE}}, /* ctrl+shift+8 */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_9, KEYS_ACTION_MOVE_TO_GROUP, {KEYS_ARG_UNIMPLEMENTED, 8, KEYS_CHORD_NONE}}, /* ctrl+shift+9 */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_bracketleft, KEYS_ACTION_FOLD, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+[ */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_bracketright, KEYS_ACTION_UNFOLD, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+] */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_a, KEYS_ACTION_SELECT_SMART, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+a */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_b, KEYS_ACTION_BUILD, {KEYS_ARG_UNIMPLEMENTED|KEYS_ARG_SELECT, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+b */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_d, KEYS_ACTION_DUPLICATE_LINE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+d */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_e, KEYS_ACTION_SLURP_REPLACE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+e */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_f, KEYS_ACTION_FIND_IN_FILES, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+f */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_h, KEYS_ACTION_REPLACE_NEXT, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+h */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_i, KEYS_ACTION_INCREMENTAL_FIND, {KEYS_ARG_UNIMPLEMENTED|KEYS_ARG_REVERSE, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+i */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_j, KEYS_ACTION_JOIN_LINES, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+j */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_k, KEYS_ACTION_DELETE_LINE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+k */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_l, KEYS_ACTION_SPLIT_SELECTION_LINES, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+l */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_m, KEYS_ACTION_SELECT_BRACKETS, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+m */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_n, KEYS_ACTION_NEW_WINDOW, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+n */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_p, KEYS_ACTION_COMMAND_PALETTE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+p */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_r, KEYS_ACTION_GOTO_PROJECT_SYMBOL, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+r */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_s, KEYS_ACTION_SAVE_AS, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+s */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_t, KEYS_ACTION_REOPEN_FILE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+t */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_u, KEYS_ACTION_SOFT_REDO, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+u */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_v, KEYS_ACTION_PASTE_AND_INDENT, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+v */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_w, KEYS_ACTION_CLOSE_WINDOW, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+w */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_z, KEYS_ACTION_REDO, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+z */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_BackSpace, KEYS_ACTION_DELETE_TO_BOL, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+backspace */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_Tab, KEYS_ACTION_PREVIOUS_VIEW_STACK, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+tab */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_Return, KEYS_ACTION_INSERT_LINE_BEFORE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+enter */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_Home, KEYS_ACTION_DOC_HOME, {KEYS_ARG_EXTEND, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+home */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_Left, KEYS_ACTION_WORD_LEFT, {KEYS_ARG_EXTEND, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+left */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_Up, KEYS_ACTION_MOVE_LINE_UP, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+up */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_Right, KEYS_ACTION_WORD_RIGHT, {KEYS_ARG_EXTEND, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+right */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_Down, KEYS_ACTION_MOVE_LINE_DOWN, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+down */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_Prior, KEYS_ACTION_PREVIOUS_VIEW, {KEYS_ARG_UNIMPLEMENTED|KEYS_ARG_EXTEND, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+pageup */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_Next, KEYS_ACTION_NEXT_VIEW, {KEYS_ARG_UNIMPLEMENTED|KEYS_ARG_EXTEND, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+pagedown */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_End, KEYS_ACTION_DOC_END, {KEYS_ARG_EXTEND, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+end */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_KP_Enter, KEYS_ACTION_INSERT_LINE_BEFORE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+keypad_enter */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_F2, KEYS_ACTION_CLEAR_BOOKMARKS, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+f2 */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_F3, KEYS_ACTION_FIND_UNDER_PREVIOUS, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+f3 */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_F6, KEYS_ACTION_PREVIOUS_MISSPELLING, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+f6 */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_F12, KEYS_ACTION_GOTO_REFERENCE, {KEYS_ARG_UNIMPLEMENTED|KEYS_ARG_SIDE_BY_SIDE, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+f12 */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_Delete, KEYS_ACTION_DELETE_TO_EOL, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+shift+delete */
    {PLAT_MOD_ALT, XKB_KEY_minus, KEYS_ACTION_JUMP_BACK, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* alt+- */
    {PLAT_MOD_ALT, XKB_KEY_period, KEYS_ACTION_CLOSE_TAG, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* alt+. */
    {PLAT_MOD_ALT, XKB_KEY_slash, KEYS_ACTION_AUTO_COMPLETE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* alt+/ */
    {PLAT_MOD_ALT, XKB_KEY_1, KEYS_ACTION_SELECT_TAB, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* alt+1 */
    {PLAT_MOD_ALT, XKB_KEY_2, KEYS_ACTION_SELECT_TAB, {KEYS_ARG_UNIMPLEMENTED, 1, KEYS_CHORD_NONE}}, /* alt+2 */
    {PLAT_MOD_ALT, XKB_KEY_3, KEYS_ACTION_SELECT_TAB, {KEYS_ARG_UNIMPLEMENTED, 2, KEYS_CHORD_NONE}}, /* alt+3 */
    {PLAT_MOD_ALT, XKB_KEY_4, KEYS_ACTION_SELECT_TAB, {KEYS_ARG_UNIMPLEMENTED, 3, KEYS_CHORD_NONE}}, /* alt+4 */
    {PLAT_MOD_ALT, XKB_KEY_5, KEYS_ACTION_SELECT_TAB, {KEYS_ARG_UNIMPLEMENTED, 4, KEYS_CHORD_NONE}}, /* alt+5 */
    {PLAT_MOD_ALT, XKB_KEY_6, KEYS_ACTION_SELECT_TAB, {KEYS_ARG_UNIMPLEMENTED, 5, KEYS_CHORD_NONE}}, /* alt+6 */
    {PLAT_MOD_ALT, XKB_KEY_7, KEYS_ACTION_SELECT_TAB, {KEYS_ARG_UNIMPLEMENTED, 6, KEYS_CHORD_NONE}}, /* alt+7 */
    {PLAT_MOD_ALT, XKB_KEY_8, KEYS_ACTION_SELECT_TAB, {KEYS_ARG_UNIMPLEMENTED, 7, KEYS_CHORD_NONE}}, /* alt+8 */
    {PLAT_MOD_ALT, XKB_KEY_9, KEYS_ACTION_SELECT_LAST_TAB, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* alt+9 */
    {PLAT_MOD_ALT, XKB_KEY_l, KEYS_ACTION_SELECT_PREVIOUS_LINE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* alt+l */
    {PLAT_MOD_ALT, XKB_KEY_o, KEYS_ACTION_SWITCH_FILE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* alt+o */
    {PLAT_MOD_ALT, XKB_KEY_q, KEYS_ACTION_WRAP_LINES, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* alt+q */
    {PLAT_MOD_ALT, XKB_KEY_Left, KEYS_ACTION_SUBWORD_LEFT, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* alt+left */
    {PLAT_MOD_ALT, XKB_KEY_Right, KEYS_ACTION_SUBWORD_RIGHT, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* alt+right */
    {PLAT_MOD_ALT, XKB_KEY_KP_Subtract, KEYS_ACTION_JUMP_BACK, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* alt+keypad_minus */
    {PLAT_MOD_ALT, XKB_KEY_F2, KEYS_ACTION_SELECT_BOOKMARKS, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* alt+f2 */
    {PLAT_MOD_ALT, XKB_KEY_F3, KEYS_ACTION_FIND_ALL_UNDER, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* alt+f3 */
    {PLAT_MOD_SHIFT|PLAT_MOD_ALT, XKB_KEY_minus, KEYS_ACTION_JUMP_FORWARD, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* alt+shift+- */
    {PLAT_MOD_SHIFT|PLAT_MOD_ALT, XKB_KEY_1, KEYS_ACTION_SET_LAYOUT, {KEYS_ARG_UNIMPLEMENTED, 1, KEYS_CHORD_NONE}}, /* alt+shift+1 */
    {PLAT_MOD_SHIFT|PLAT_MOD_ALT, XKB_KEY_2, KEYS_ACTION_SET_LAYOUT, {KEYS_ARG_UNIMPLEMENTED, 2, KEYS_CHORD_NONE}}, /* alt+shift+2 */
    {PLAT_MOD_SHIFT|PLAT_MOD_ALT, XKB_KEY_3, KEYS_ACTION_SET_LAYOUT, {KEYS_ARG_UNIMPLEMENTED, 3, KEYS_CHORD_NONE}}, /* alt+shift+3 */
    {PLAT_MOD_SHIFT|PLAT_MOD_ALT, XKB_KEY_4, KEYS_ACTION_SET_LAYOUT, {KEYS_ARG_UNIMPLEMENTED, 4, KEYS_CHORD_NONE}}, /* alt+shift+4 */
    {PLAT_MOD_SHIFT|PLAT_MOD_ALT, XKB_KEY_5, KEYS_ACTION_SET_LAYOUT, {KEYS_ARG_UNIMPLEMENTED, 5, KEYS_CHORD_NONE}}, /* alt+shift+5 */
    {PLAT_MOD_SHIFT|PLAT_MOD_ALT, XKB_KEY_8, KEYS_ACTION_SET_LAYOUT, {KEYS_ARG_UNIMPLEMENTED, 8, KEYS_CHORD_NONE}}, /* alt+shift+8 */
    {PLAT_MOD_SHIFT|PLAT_MOD_ALT, XKB_KEY_9, KEYS_ACTION_SET_LAYOUT, {KEYS_ARG_UNIMPLEMENTED, 9, KEYS_CHORD_NONE}}, /* alt+shift+9 */
    {PLAT_MOD_SHIFT|PLAT_MOD_ALT, XKB_KEY_o, KEYS_ACTION_SWITCH_FILE, {KEYS_ARG_UNIMPLEMENTED|KEYS_ARG_SIDE_BY_SIDE, 0, KEYS_CHORD_NONE}}, /* alt+shift+o */
    {PLAT_MOD_SHIFT|PLAT_MOD_ALT, XKB_KEY_w, KEYS_ACTION_XML_TAG_SNIPPET, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* alt+shift+w */
    {PLAT_MOD_SHIFT|PLAT_MOD_ALT, XKB_KEY_Left, KEYS_ACTION_SUBWORD_LEFT, {KEYS_ARG_UNIMPLEMENTED|KEYS_ARG_EXTEND, 0, KEYS_CHORD_NONE}}, /* alt+shift+left */
    {PLAT_MOD_SHIFT|PLAT_MOD_ALT, XKB_KEY_Up, KEYS_ACTION_COLUMN_SELECTION, {KEYS_ARG_UNIMPLEMENTED, -1, KEYS_CHORD_NONE}}, /* alt+shift+up */
    {PLAT_MOD_SHIFT|PLAT_MOD_ALT, XKB_KEY_Right, KEYS_ACTION_SUBWORD_RIGHT, {KEYS_ARG_UNIMPLEMENTED|KEYS_ARG_EXTEND, 0, KEYS_CHORD_NONE}}, /* alt+shift+right */
    {PLAT_MOD_SHIFT|PLAT_MOD_ALT, XKB_KEY_Down, KEYS_ACTION_COLUMN_SELECTION, {KEYS_ARG_UNIMPLEMENTED, 1, KEYS_CHORD_NONE}}, /* alt+shift+down */
    {PLAT_MOD_SHIFT|PLAT_MOD_ALT, XKB_KEY_KP_Subtract, KEYS_ACTION_JUMP_FORWARD, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* alt+shift+keypad_minus */
    {PLAT_MOD_CTRL|PLAT_MOD_ALT, XKB_KEY_p, KEYS_ACTION_SELECT_WORKSPACE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+alt+p */
    {PLAT_MOD_CTRL|PLAT_MOD_ALT, XKB_KEY_q, KEYS_ACTION_RECORD_MACRO, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+alt+q */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL|PLAT_MOD_ALT, XKB_KEY_p, KEYS_ACTION_SHOW_SCOPE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+alt+shift+p */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL|PLAT_MOD_ALT, XKB_KEY_q, KEYS_ACTION_RUN_MACRO, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_NONE}}, /* ctrl+alt+shift+q */
    {PLAT_MOD_CTRL, XKB_KEY_space, KEYS_ACTION_SET_MARK, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_K}}, /* ctrl+k ctrl+space */
    {PLAT_MOD_CTRL, XKB_KEY_slash, KEYS_ACTION_INLINE_DIFF, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_K}}, /* ctrl+k ctrl+/ */
    {PLAT_MOD_CTRL, XKB_KEY_0, KEYS_ACTION_UNFOLD_ALL, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_K}}, /* ctrl+k ctrl+0 */
    {PLAT_MOD_CTRL, XKB_KEY_1, KEYS_ACTION_FOLD_LEVEL, {KEYS_ARG_UNIMPLEMENTED, 1, KEYS_CHORD_K}}, /* ctrl+k ctrl+1 */
    {PLAT_MOD_CTRL, XKB_KEY_2, KEYS_ACTION_FOLD_LEVEL, {KEYS_ARG_UNIMPLEMENTED, 2, KEYS_CHORD_K}}, /* ctrl+k ctrl+2 */
    {PLAT_MOD_CTRL, XKB_KEY_3, KEYS_ACTION_FOLD_LEVEL, {KEYS_ARG_UNIMPLEMENTED, 3, KEYS_CHORD_K}}, /* ctrl+k ctrl+3 */
    {PLAT_MOD_CTRL, XKB_KEY_4, KEYS_ACTION_FOLD_LEVEL, {KEYS_ARG_UNIMPLEMENTED, 4, KEYS_CHORD_K}}, /* ctrl+k ctrl+4 */
    {PLAT_MOD_CTRL, XKB_KEY_5, KEYS_ACTION_FOLD_LEVEL, {KEYS_ARG_UNIMPLEMENTED, 5, KEYS_CHORD_K}}, /* ctrl+k ctrl+5 */
    {PLAT_MOD_CTRL, XKB_KEY_6, KEYS_ACTION_FOLD_LEVEL, {KEYS_ARG_UNIMPLEMENTED, 6, KEYS_CHORD_K}}, /* ctrl+k ctrl+6 */
    {PLAT_MOD_CTRL, XKB_KEY_7, KEYS_ACTION_FOLD_LEVEL, {KEYS_ARG_UNIMPLEMENTED, 7, KEYS_CHORD_K}}, /* ctrl+k ctrl+7 */
    {PLAT_MOD_CTRL, XKB_KEY_8, KEYS_ACTION_FOLD_LEVEL, {KEYS_ARG_UNIMPLEMENTED, 8, KEYS_CHORD_K}}, /* ctrl+k ctrl+8 */
    {PLAT_MOD_CTRL, XKB_KEY_9, KEYS_ACTION_FOLD_LEVEL, {KEYS_ARG_UNIMPLEMENTED, 9, KEYS_CHORD_K}}, /* ctrl+k ctrl+9 */
    {PLAT_MOD_CTRL, XKB_KEY_semicolon, KEYS_ACTION_INLINE_DIFF, {KEYS_ARG_UNIMPLEMENTED|KEYS_ARG_PREFER_HIDE, 0, KEYS_CHORD_K}}, /* ctrl+k ctrl+; */
    {PLAT_MOD_CTRL, XKB_KEY_bracketright, KEYS_ACTION_REINDENT, {KEYS_ARG_UNIMPLEMENTED|KEYS_ARG_SINGLE_LINE, 0, KEYS_CHORD_K}}, /* ctrl+k ctrl+] */
    {PLAT_MOD_CTRL, XKB_KEY_a, KEYS_ACTION_SELECT_TO_MARK, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_K}}, /* ctrl+k ctrl+a */
    {PLAT_MOD_CTRL, XKB_KEY_b, KEYS_ACTION_TOGGLE_SIDEBAR, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_K}}, /* ctrl+k ctrl+b */
    {PLAT_MOD_CTRL, XKB_KEY_c, KEYS_ACTION_SHOW_AT_CENTER, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_K}}, /* ctrl+k ctrl+c */
    {PLAT_MOD_CTRL, XKB_KEY_d, KEYS_ACTION_SKIP_NEXT_OCCURRENCE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_K}}, /* ctrl+k ctrl+d */
    {PLAT_MOD_CTRL, XKB_KEY_g, KEYS_ACTION_CLEAR_MARK, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_K}}, /* ctrl+k ctrl+g */
    {PLAT_MOD_CTRL, XKB_KEY_j, KEYS_ACTION_UNFOLD_ALL, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_K}}, /* ctrl+k ctrl+j */
    {PLAT_MOD_CTRL, XKB_KEY_k, KEYS_ACTION_DELETE_TO_EOL, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_K}}, /* ctrl+k ctrl+k */
    {PLAT_MOD_CTRL, XKB_KEY_l, KEYS_ACTION_LOWER_CASE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_K}}, /* ctrl+k ctrl+l */
    {PLAT_MOD_CTRL, XKB_KEY_t, KEYS_ACTION_FOLD_TAG_ATTRIBUTES, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_K}}, /* ctrl+k ctrl+t */
    {PLAT_MOD_CTRL, XKB_KEY_u, KEYS_ACTION_UPPER_CASE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_K}}, /* ctrl+k ctrl+u */
    {PLAT_MOD_CTRL, XKB_KEY_v, KEYS_ACTION_PASTE_HISTORY, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_K}}, /* ctrl+k ctrl+v */
    {PLAT_MOD_CTRL, XKB_KEY_w, KEYS_ACTION_DELETE_TO_MARK, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_K}}, /* ctrl+k ctrl+w */
    {PLAT_MOD_CTRL, XKB_KEY_x, KEYS_ACTION_SWAP_MARK, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_K}}, /* ctrl+k ctrl+x */
    {PLAT_MOD_CTRL, XKB_KEY_y, KEYS_ACTION_YANK, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_K}}, /* ctrl+k ctrl+y */
    {PLAT_MOD_CTRL, XKB_KEY_z, KEYS_ACTION_REVERT_HUNK, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_K}}, /* ctrl+k ctrl+z */
    {PLAT_MOD_CTRL, XKB_KEY_BackSpace, KEYS_ACTION_DELETE_TO_BOL, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_K}}, /* ctrl+k ctrl+backspace */
    {PLAT_MOD_CTRL, XKB_KEY_Left, KEYS_ACTION_FOCUS_NEIGHBOR_GROUP, {KEYS_ARG_UNIMPLEMENTED, -1, KEYS_CHORD_K}}, /* ctrl+k ctrl+left */
    {PLAT_MOD_CTRL, XKB_KEY_Up, KEYS_ACTION_NEW_PANE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_K}}, /* ctrl+k ctrl+up */
    {PLAT_MOD_CTRL, XKB_KEY_Right, KEYS_ACTION_FOCUS_NEIGHBOR_GROUP, {KEYS_ARG_UNIMPLEMENTED, 1, KEYS_CHORD_K}}, /* ctrl+k ctrl+right */
    {PLAT_MOD_CTRL, XKB_KEY_Down, KEYS_ACTION_CLOSE_PANE, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_K}}, /* ctrl+k ctrl+down */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_z, KEYS_ACTION_REVERT_MODIFICATION, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_K}}, /* ctrl+k ctrl+shift+z */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_Left, KEYS_ACTION_MOVE_NEIGHBOR_GROUP, {KEYS_ARG_UNIMPLEMENTED, -1, KEYS_CHORD_K}}, /* ctrl+k ctrl+shift+left */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_Up, KEYS_ACTION_NEW_PANE, {KEYS_ARG_UNIMPLEMENTED|KEYS_ARG_NO_MOVE, 0, KEYS_CHORD_K}}, /* ctrl+k ctrl+shift+up */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_Right, KEYS_ACTION_MOVE_NEIGHBOR_GROUP, {KEYS_ARG_UNIMPLEMENTED, 1, KEYS_CHORD_K}}, /* ctrl+k ctrl+shift+right */
    {PLAT_MOD_CTRL, XKB_KEY_j, KEYS_ACTION_PRIMARY_J_CHANGED, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_J}}, /* ctrl+j ctrl+j */
    {PLAT_MOD_CTRL, XKB_KEY_Left, KEYS_ACTION_UNSELECT_LEFT, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_J}}, /* ctrl+j ctrl+left */
    {PLAT_MOD_CTRL, XKB_KEY_Up, KEYS_ACTION_UNSELECT_OTHERS, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_J}}, /* ctrl+j ctrl+up */
    {PLAT_MOD_CTRL, XKB_KEY_Right, KEYS_ACTION_UNSELECT_RIGHT, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_J}}, /* ctrl+j ctrl+right */
    {PLAT_MOD_CTRL, XKB_KEY_Prior, KEYS_ACTION_FOCUS_LEFT, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_J}}, /* ctrl+j ctrl+pageup */
    {PLAT_MOD_CTRL, XKB_KEY_Next, KEYS_ACTION_FOCUS_RIGHT, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_J}}, /* ctrl+j ctrl+pagedown */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_Left, KEYS_ACTION_SELECT_LEFT, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_J}}, /* ctrl+j ctrl+shift+left */
    {PLAT_MOD_SHIFT|PLAT_MOD_CTRL, XKB_KEY_Right, KEYS_ACTION_SELECT_RIGHT, {KEYS_ARG_UNIMPLEMENTED, 0, KEYS_CHORD_J}}, /* ctrl+j ctrl+shift+right */
};

void keys_reset(keys_state *state)
{
    if (state) state->chord=KEYS_CHORD_NONE;
}
const keys_binding *keys_defaults(size_t *count)
{
    if (count) *count=sizeof defaults/sizeof defaults[0];
    return defaults;
}
static int modifier_key(uint32_t sym)
{
    return (sym>=XKB_KEY_Shift_L && sym<=XKB_KEY_Hyper_R) ||
        sym==XKB_KEY_Num_Lock || sym==XKB_KEY_Mode_switch ||
        sym==XKB_KEY_ISO_Level3_Shift || sym==XKB_KEY_ISO_Level5_Shift;
}
static uint32_t canonical(uint32_t sym, uint16_t *mods)
{
    if (sym>=XKB_KEY_A && sym<=XKB_KEY_Z) sym+=XKB_KEY_a-XKB_KEY_A;
    switch (sym) {
    case XKB_KEY_ISO_Left_Tab: sym=XKB_KEY_Tab; *mods|=PLAT_MOD_SHIFT; break;
    case XKB_KEY_KP_Home: sym=XKB_KEY_Home; break;
    case XKB_KEY_KP_Left: sym=XKB_KEY_Left; break;
    case XKB_KEY_KP_Up: sym=XKB_KEY_Up; break;
    case XKB_KEY_KP_Right: sym=XKB_KEY_Right; break;
    case XKB_KEY_KP_Down: sym=XKB_KEY_Down; break;
    case XKB_KEY_KP_Prior: sym=XKB_KEY_Prior; break;
    case XKB_KEY_KP_Next: sym=XKB_KEY_Next; break;
    case XKB_KEY_KP_End: sym=XKB_KEY_End; break;
    case XKB_KEY_KP_Insert: sym=XKB_KEY_Insert; break;
    case XKB_KEY_KP_Delete: sym=XKB_KEY_Delete; break;
    default: break;
    }
    /* Input keysyms already have Shift applied. Undo US punctuation shifts
     * only on shortcuts. Keep Shift as a binding modifier, except the literal
     * ctrl++ default, whose plus normally requires Shift on a US keyboard. */
    if ((*mods & (PLAT_MOD_SHIFT|PLAT_MOD_CTRL|PLAT_MOD_ALT|PLAT_MOD_SUPER))==
        (PLAT_MOD_SHIFT|PLAT_MOD_CTRL) && sym==XKB_KEY_plus) {
        *mods=(uint16_t)(*mods & (uint16_t)~PLAT_MOD_SHIFT);
        return sym;
    }
    if ((*mods & PLAT_MOD_SHIFT) && (*mods & (PLAT_MOD_CTRL|PLAT_MOD_ALT|PLAT_MOD_SUPER))) {
        switch (sym) {
        case XKB_KEY_exclam: sym=XKB_KEY_1; break;
        case XKB_KEY_at: sym=XKB_KEY_2; break;
        case XKB_KEY_numbersign: sym=XKB_KEY_3; break;
        case XKB_KEY_dollar: sym=XKB_KEY_4; break;
        case XKB_KEY_percent: sym=XKB_KEY_5; break;
        case XKB_KEY_asciicircum: sym=XKB_KEY_6; break;
        case XKB_KEY_ampersand: sym=XKB_KEY_7; break;
        case XKB_KEY_asterisk: sym=XKB_KEY_8; break;
        case XKB_KEY_parenleft: sym=XKB_KEY_9; break;
        case XKB_KEY_parenright: sym=XKB_KEY_0; break;
        case XKB_KEY_underscore: sym=XKB_KEY_minus; break;
        case XKB_KEY_plus: sym=XKB_KEY_equal; break;
        case XKB_KEY_braceleft: sym=XKB_KEY_bracketleft; break;
        case XKB_KEY_braceright: sym=XKB_KEY_bracketright; break;
        case XKB_KEY_bar: sym=XKB_KEY_backslash; break;
        case XKB_KEY_colon: sym=XKB_KEY_semicolon; break;
        case XKB_KEY_quotedbl: sym=XKB_KEY_apostrophe; break;
        case XKB_KEY_less: sym=XKB_KEY_comma; break;
        case XKB_KEY_greater: sym=XKB_KEY_period; break;
        case XKB_KEY_question: sym=XKB_KEY_slash; break;
        case XKB_KEY_asciitilde: sym=XKB_KEY_grave; break;
        default: break;
        }
    }
    return sym;
}
static const keys_binding *find_binding(uint8_t chord, uint16_t mods, uint32_t sym)
{
    size_t lo=0, hi=sizeof defaults/sizeof defaults[0];
    while (lo<hi) {
        size_t mid=lo+(hi-lo)/2; const keys_binding *b=&defaults[mid];
        if (chord==b->args.chord && mods==b->modifiers && sym==b->keysym) return b;
        if (chord<b->args.chord || (chord==b->args.chord &&
            (mods<b->modifiers || (mods==b->modifiers && sym<b->keysym)))) hi=mid;
        else lo=mid+1;
    }
    return NULL;
}
keys_result keys_lookup(keys_state *state, uint32_t keysym, uint16_t modifiers,
                        const keys_binding **out)
{
    if (out) *out=NULL;
    if (!state || !out) return KEYS_ERR_ARG;
    if (state->chord>=KEYS_CHORD_COUNT) keys_reset(state);
    if (modifier_key(keysym)) return KEYS_NONE;
    uint8_t chord=state->chord;
    keys_reset(state);
    modifiers=(uint16_t)(modifiers & (uint16_t)~(PLAT_MOD_CAPS|PLAT_MOD_NUM));
    if (modifiers & (uint16_t)~(PLAT_MOD_SHIFT|PLAT_MOD_CTRL|PLAT_MOD_ALT|PLAT_MOD_SUPER))
        return chord?KEYS_CANCELLED:KEYS_NONE;
    keysym=canonical(keysym,&modifiers);
    const keys_binding *b=find_binding(chord,modifiers,keysym);
    if (!b) return chord?KEYS_CANCELLED:KEYS_NONE;
    *out=b;
    if (b->action==KEYS_ACTION_CHORD) {
        state->chord=(uint8_t)b->args.value;
        return KEYS_PREFIX;
    }
    return KEYS_MATCH;
}
