/* tools/atlasbake.c - bakes the ASCII atlas header (P2.3, edit-e6x.3).
 * usage: atlasbake <font.ttf> <px> <out.h>
 * Output is deterministic: no timestamps, fixed formatting. */
#include "base/base.h"
#include "font/font.h"
#include <stdio.h>
#include <string.h>


#define FONT_ASCII_FIRST_ 0x20u
#define FONT_ASCII_LAST_  0x7Eu
#define ASCII_COUNT (FONT_ASCII_LAST_ - FONT_ASCII_FIRST_ + 1)
#define ARENA_BYTES (1u << 20)

static unsigned char *read_file(const char *path, size_t *len)
{
    FILE *fp = fopen(path, "rb");
    if (!fp) return NULL;
    unsigned char *buf = NULL;
    long n = 0;
    if (fseek(fp, 0, SEEK_END) != 0) goto fail;
    n = ftell(fp);
    if (n <= 0 || fseek(fp, 0, SEEK_SET) != 0) goto fail;
    buf = malloc((size_t)n); /* build tool, not on the typing path */
    if (!buf || fread(buf, 1, (size_t)n, fp) != (size_t)n) goto fail;
    fclose(fp);
    *len = (size_t)n;
    return buf;
fail:
    free(buf);
    fclose(fp);
    return NULL;
}

int main(int argc, char **argv)
{
    if (argc != 4) {
        fprintf(stderr, "usage: %s <font.ttf> <px> <out.h>\n", argv[0]);
        return 2;
    }
    unsigned long px = strtoul(argv[2], NULL, 10);
    if (px == 0 || px > 4096) {
        fprintf(stderr, "atlasbake: bad px %s\n", argv[2]);
        return 2;
    }
    size_t len = 0;
    unsigned char *ttf = read_file(argv[1], &len);
    if (!ttf) {
        fprintf(stderr, "atlasbake: cannot read %s\n", argv[1]);
        return 1;
    }
    font_t f;
    if (font_init(&f, ttf, len) != FONT_OK || font_set_px(&f, (uint32_t)px) != FONT_OK) {
        fprintf(stderr, "atlasbake: bad font %s\n", argv[1]);
        return 1;
    }
    font_cell cell;
    font_cell_metrics(&f, &cell);
    uint32_t cw = cell.cell_w, ch = cell.cell_h;
    size_t pix_len = (size_t)ASCII_COUNT * cw * ch;
    uint8_t *pix = calloc(pix_len, 1); /* build tool */
    font_metric *mets = calloc(ASCII_COUNT, sizeof *mets);
    edit_arena arena;
    if (!pix || !mets || edit_arena_init(&arena, ARENA_BYTES) != 0) return 1;

    for (uint32_t i = 0; i < ASCII_COUNT; i++) {
        uint32_t cp = FONT_ASCII_FIRST_ + i;
        font_bitmap b;
        edit_arena_mark_t mk = edit_arena_mark(&arena);
        if (font_raster_glyph(&f, cp, &arena, &b) != FONT_OK) {
            fprintf(stderr, "atlasbake: U+%04X missing in font\n", cp);
            return 1;
        }
        mets[i] = b.m;
        font_place_in_cell(&f, &b, pix + (size_t)i * cw * ch, cw, ch);
        /* the row of cells is one contiguous R8 strip: cell i at x = i*cw */
        edit_arena_reset_to_mark(&arena, mk);
    }
    /* Row layout: rearrange cells into one row of width ASCII_COUNT*cw. */
    size_t row_w = (size_t)ASCII_COUNT * cw;
    uint8_t *row = calloc(pix_len, 1);
    if (!row) return 1;
    for (uint32_t i = 0; i < ASCII_COUNT; i++)
        for (uint32_t y = 0; y < ch; y++)
            memcpy(row + (size_t)y * row_w + (size_t)i * cw,
                   pix + (size_t)i * cw * ch + (size_t)y * cw, cw);

    FILE *out = fopen(argv[3], "w");
    if (!out) return 1;
    fprintf(out, "/* src/font/atlas_ascii.h - GENERATED by tools/atlasbake. Do not edit.\n"
                 " * font: DejaVuSansMono.ttf  px: %lu  range: U+0020..U+007E\n"
                 " * Atlas is one R8 row of %u cells of %ux%u px (cell i at x = i*%u). */\n",
            px, ASCII_COUNT, cw, ch, cw);
    fprintf(out, "#define FONT_ATLAS_PX %lu\n", px);
    fprintf(out, "#define FONT_ATLAS_CELL_W %u\n", cw);
    fprintf(out, "#define FONT_ATLAS_CELL_H %u\n", ch);
    fprintf(out, "#define FONT_ATLAS_ASCENT %u\n", cell.ascent);
    fprintf(out, "const font_metric font_atlas_metrics[%u] = {\n", ASCII_COUNT);
    for (uint32_t i = 0; i < ASCII_COUNT; i++)
        fprintf(out, "    { %d, %d, %d, %u, %u },\n", (int)mets[i].advance,
                (int)mets[i].bearing_x, (int)mets[i].bearing_y, mets[i].w, mets[i].h);
    fprintf(out, "};\n");
    fprintf(out, "const uint8_t font_atlas_pixels[%zu] = {\n", pix_len);
    for (size_t i = 0; i < pix_len; i++) {
        if (i % 16 == 0) fprintf(out, "   ");
        fprintf(out, " 0x%02x,", row[i]);
        if (i % 16 == 15 || i + 1 == pix_len) fprintf(out, "\n");
    }
    fprintf(out, "};\n");
    fclose(out);
    edit_arena_free(&arena);
    free(pix); free(row); free(mets); free(ttf);
    return 0;
}
